# Site
name: 'Is a ac'
description: 'a personal blog website!'
logo: 'assets/images/web-logo.ico'
favicon: 'assets/images/web-logo.ico'
disqus: 'demowebsite'
email: 'isaachuang.bc@icloud.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    isaac:
      name:           Isaac
      site:           https://isaachuan9.github.io
      avatar:         /assets/images/isaac_photo.jpg
      bio:            "那轰然一响，我们也是星辰。"
      email:          isaachuang.bc@icloud.com
      twitter:        
 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: isaac
      avatar: /assets/images/isaac_photo.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

cities:
  - guangzhou


# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, _test]